//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamP1JG.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class examenDBEntities : DbContext
    {
        public examenDBEntities()
            : base("name=examenDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_categoria> tbl_categoria { get; set; }
        public virtual DbSet<tbl_genelResultados> tbl_genelResultados { get; set; }
        public virtual DbSet<tbl_opcion> tbl_opcion { get; set; }
        public virtual DbSet<tbl_pregunta> tbl_pregunta { get; set; }
        public virtual DbSet<tbl_resultadoExam> tbl_resultadoExam { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
    }
}
