//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamP1JG.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_resultadoExam
    {
        public int id_examen { get; set; }
        public Nullable<bool> esCorrecto { get; set; }
        public Nullable<int> id_categoria { get; set; }
        public Nullable<int> punto { get; set; }
        public Nullable<System.DateTime> historialExamen { get; set; }
        public Nullable<System.Guid> preguntaUniq { get; set; }
        public Nullable<int> examenUniq { get; set; }
        public Nullable<int> examenNo { get; set; }
    
        public virtual tbl_genelResultados tbl_genelResultados { get; set; }
    }
}
