//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamP1JG.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pregunta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_pregunta()
        {
            this.tbl_opcion = new HashSet<tbl_opcion>();
        }
    
        public System.Guid preguntaUniq { get; set; }
        public string pregunta { get; set; }
        public Nullable<int> descripcion { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual tbl_categoria tbl_categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_opcion> tbl_opcion { get; set; }
    }
}
