//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamP1JG.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_genelResultados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_genelResultados()
        {
            this.tbl_resultadoExam = new HashSet<tbl_resultadoExam>();
        }
    
        public int examenUniq { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> quizCount { get; set; }
    
        public virtual tbl_usuario tbl_usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_resultadoExam> tbl_resultadoExam { get; set; }
    }
}
