//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamP1JG.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_opcion
    {
        public int id_Respuesta { get; set; }
        public string respuesta1 { get; set; }
        public string respuesta2 { get; set; }
        public string respuesta3 { get; set; }
        public string respuesta4 { get; set; }
        public string correctaRsp { get; set; }
        public Nullable<System.Guid> preguntaUniq { get; set; }
    
        public virtual tbl_pregunta tbl_pregunta { get; set; }
    }
}
